#expiration_time : The expiration date of the token
# secret : Required for creating JWT tokens and validating JWT tokens

server:
  port: 0

spring:
  application:
    name: user-service
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password: sa

token:
  expiration_time: 864000000 
  secret: user_token

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
